---
####################################################
#          ModuleBuilder Configuration             #
####################################################

SourcePath: source
CopyPaths:
  - en-US
Encoding: UTF8
VersionedOutputDirectory: true
Prefix: prefix.ps1
Suffix: suffix.ps1

####################################################
#              Pipeline Configuration              #
####################################################

BuildWorkflow:
  '.':
    - build
    - test

  build:
    - Clean
    - Build_ModuleOutput_ModuleBuilder
    - Build_SingleFile_Distribution

  test:
    - Pester_Tests_Stop_On_Fail

  publish:
    - publish_module_to_gallery

####################################################
#       Sampler Pipeline Configuration             #
####################################################

Sampler:
  DefaultOutputDirectory: 'output'

ModuleBuildTasks:
  Sampler:
    - '*.build.Sampler.ib.tasks'
  ModuleBuilder:
    - '*.build.ModuleBuilder.ib.tasks'

TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

####################################################
#       PESTER Configuration                       #
####################################################

Pester:
  Script:
    - Tests
  ExcludeTag:
    - Live
    - Integration
  Tag:
  OutputFile: output/testResults/testResults.xml
  OutputFormat: NUnitXml
  PassThru: true

####################################################
#       PSScriptAnalyzer Configuration            #
####################################################

PSScriptAnalyzer:
  Script: source
  Settings: .PSScriptAnalyzerSettings.psd1
  ExcludeRule:
  IncludeRule:
